# Generated by Django 4.2.16 on 2024-11-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='邮箱验证码'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_code_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='验证码过期时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='邮箱已验证'),
        ),
    ]
