# Generated by Django 4.2.16 on 2024-12-08 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aimodels', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='对话标题')),
                ('conversation_type', models.CharField(choices=[('history', '历史记录'), ('temporary', '临时记录')], max_length=20, verbose_name='对话类型')),
                ('status', models.CharField(choices=[('active', '活跃'), ('deleted', '已删除')], default='active', max_length=20, verbose_name='状态')),
                ('expire_time', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('last_message_time', models.DateTimeField(blank=True, null=True, verbose_name='最后消息时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aimodels.aimodel', verbose_name='AI模型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '对话记录',
                'verbose_name_plural': '对话记录',
                'db_table': 'chat_conversations',
            },
        ),
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_type', models.CharField(choices=[('history', '历史记录'), ('temporary', '临时记录')], max_length=20, unique=True, verbose_name='设置类型')),
                ('duration_days', models.IntegerField(default=0, verbose_name='持续时间(天)')),
                ('duration_hours', models.IntegerField(default=0, verbose_name='持续时间(小时)')),
                ('duration_minutes', models.IntegerField(default=0, verbose_name='持续时间(分钟)')),
                ('is_permanent', models.BooleanField(default=False, verbose_name='是否永久保存')),
                ('max_records', models.IntegerField(verbose_name='最大保存记录数')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.TextField(blank=True, null=True, verbose_name='设置说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chat_settings', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_chat_settings', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '对话设置',
                'verbose_name_plural': '对话设置',
                'db_table': 'chat_settings',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', 'AI助手')], max_length=20, verbose_name='发送者角色')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('message_type', models.CharField(choices=[('text', '文本'), ('image', '图片'), ('code', '代码')], default='text', max_length=20, verbose_name='消息类型')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='额外元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatconversation', verbose_name='对话')),
            ],
            options={
                'verbose_name': '对话消息',
                'verbose_name_plural': '对话消息',
                'db_table': 'chat_messages',
                'indexes': [models.Index(fields=['conversation', 'role', 'created_at'], name='chat_messag_convers_f7bb84_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletion_type', models.CharField(choices=[('user_initiated', '用户删除'), ('system_auto', '系统自动删除')], max_length=20, verbose_name='删除类型')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, verbose_name='删除时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatconversation', verbose_name='对话')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '删除日志',
                'verbose_name_plural': '删除日志',
                'db_table': 'chat_deletion_logs',
                'indexes': [models.Index(fields=['user', 'deleted_at'], name='chat_deleti_user_id_a5bc0f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['user', 'conversation_type'], name='chat_conver_user_id_08beef_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['expire_time'], name='chat_conver_expire__296bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['status'], name='chat_conver_status_5e91e7_idx'),
        ),
    ]
