# Generated by Django 4.2.16 on 2024-11-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatsession_options_remove_chatsession_model_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatSession',
        ),
    ]
