# Generated by Django 4.2.16 on 2024-11-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('chat', '对话'), ('image', '图像')], max_length=10, verbose_name='模型类型')),
                ('model_name', models.CharField(max_length=50, verbose_name='模型名称')),
                ('platform', models.CharField(choices=[('bigmodel', 'BigModel'), ('qianfan', '百度千帆'), ('spark', '讯飞星火'), ('silicon', 'SiliconCloud')], max_length=20, verbose_name='模型平台')),
                ('is_active', models.BooleanField(choices=[(True, '启用'), (False, '停用')], default=True, verbose_name='模型状态')),
                ('weight', models.IntegerField(unique=True, verbose_name='模型权重')),
                ('config', models.JSONField(default=dict, verbose_name='模型配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('original_model_name', models.CharField(blank=True, max_length=100, verbose_name='原始模型名称')),
            ],
            options={
                'verbose_name': '模型管理',
                'verbose_name_plural': '模型管理',
                'ordering': ['weight'],
            },
        ),
    ]
