# Generated by Django 4.2.16 on 2024-11-19 09:28

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_remove_announcement_show_modal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='内容'),
        ),
    ]
